# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: "5"
    - nodejs_version: "4"
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - node --version && npm --version
  - ps: >-
      if ($env:nodejs_version -eq "0.10") {
        npm -g install npm@2
        $env:PATH="$env:APPDATA\npm;$env:PATH"
      }
  - npm test

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\npm-cache -> package.json'       # npm cache
  - 'node_modules -> package.json'              # local npm modules
